### ISSUE TITLE
Game Ceme - "Jackpot" hiển thị sai vị trí

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#10]
Chữ Jackpot được khoanh tròn trong hình đã hiện không đúng vị trí hiển thị của nó hoặc nó không chữ "Jackpot" chỉ show tại vị trí user.

![jp](https://cloud.githubusercontent.com/assets/22518984/19373363/89b68ae6-91ed-11e6-8323-b7f3804ee6c3.PNG)

**Comment by dunglumy123** [comment]
đã fix
