### ISSUE TITLE
Game Domino QQ - Confirm popup hiện sai.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#103]
Popup mở ra cả với người không tham gia ván bài or đã "Fold".

**Comment by thaopvdinosys** [comment]
fixed

**Comment by TrhmTan** [comment]
Vẫn còn xuất hiện đối với User hok tham gia ván bài.
![confirm01](https://cloud.githubusercontent.com/assets/22518984/20167376/b319054c-a74d-11e6-8373-ef3de115b5f2.PNG)

**Comment by TrhmTan** [comment]
@dunglumy123 Update 3:00'
User1 ngồi trong bàn nhưng vẫn chưa tham gia Game vì vào lúc giữa Game: Không thấy Confirm popup.
User2 chưa ngồi vào bàn, chỉ đang theo dõi Game: Thấy Confirm popup xuất hiện như hình trên.
