### ISSUE TITLE
Game Ceme - Thẻ bài Jackpot chạy sai.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#11]
Những thẻ bài được tính là Jackpot khi nó là thẻ "00-01" và "65-66", 
Nhưng Jackpot lại tính cho thẻ bài "56-56".

![jp1](https://cloud.githubusercontent.com/assets/22518984/19373348/63bbab8c-91ed-11e6-8294-03e97241659b.png)

**Comment by dunglumy123** [comment]
đã fix
