### ISSUE TITLE
Game Ceme vs Game Poker - Xuất hiện những item lạ khi User select room.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#110]
Poker:
![bug_bet](https://cloud.githubusercontent.com/assets/22518984/20258937/a7d6c50e-aa84-11e6-8543-031e7d9ca2fb.PNG)

Ceme:
![bug coin](https://cloud.githubusercontent.com/assets/22518984/20258943/af6e8ef0-aa84-11e6-8386-3004dd5403e7.PNG)

**Comment by TrhmTan** [comment]
Game Ceme vẫn còn bug, @thaopvdinosys a.Thảo!

**Comment by thaopvdinosys** [comment]
fixed
