### ISSUE TITLE
Game Ceme - Khi Bandar hoặc người chơi khác thoát game trước khi chia bài.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#119]
Không cần chia bài (No open card.)
Bandar thoát game khi tắt trình duyệt. --> Tất cả User trong bàn đã đặt bet đều win.
Bug: nhưng thực tế lại, ko end game - Viewer từ ngoài vào room thì thấy đang chờ set Bandar.
![bandar quit](https://cloud.githubusercontent.com/assets/22518984/22722546/75f98fb8-edea-11e6-9441-111525916f09.PNG)

**Comment by TrhmTan** [comment]
Khi Card chưa chia, Bandar out game vì tắt browser thì các User trong bàn win nhưng Card không cần show vì Card chưa được chia.
Xem clip vào giây thứ 51s.
Video: `https://drive.google.com/open?id=0B1NczfWkep_qMlQyQXV1SG0tNFk`
![dont_show_card](https://cloud.githubusercontent.com/assets/22518984/21176721/93cb912c-c21a-11e6-8fa3-e739f2d49217.PNG)

**Comment by hiep2x** [comment]
@TrhmTan  a check lại thấy khi Bandar out game = cách tắt trình duyệt thì game dừng lại, hiển thị "Waiting for bandar", ko có tổng kết nhé. Em check lại bug này hộ anh.

**Comment by TrhmTan** [comment]
Check lại thực trạng khi bài chưa chia thì Bandar out game bằng cách tắt browser, 
Bug: Player bet và Viewer vẫn thấy Bandar trong bàn, timeline chạy hết và game vẫn không kết thúc.
