### ISSUE TITLE
Login page.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#12]
Khi login với một tài khoản không hợp lệ. 
Click login - Một thông báo hiện ra.
Nhưng cái text: tên account - ký tự password, chúng hiện chồng trên thông báo.

![login_2](https://cloud.githubusercontent.com/assets/22518984/19373301/2989a040-91ed-11e6-9cf3-b1d0894845d5.PNG)

**Comment by hiep2x** [comment]
đã fix & commit svn
