### ISSUE TITLE
Game Poker - Không ngữa bài

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#13]
Khi kết thúc 1 ván bằng việc các user bỏ bài (fold), và chỉ còn lại 1 user thì người này được xem là đã thắng. Khi đó bài của người đó vẫn phải úp, không được ngữa bài như hiện tại.

![upbai](https://cloud.githubusercontent.com/assets/22518984/19347322/6bf14738-9172-11e6-904b-0fe814fc64bd.PNG)

**Comment by nguyenphuquang** [comment]
Tân phải share cái file docs cho a (nguyenphuquang@gmail.com). Nếu là ảnh thì e gửi thẳng lên trên này cũng được.

**Comment by TrhmTan** [comment]
Dạ, e add thẳng hình vào luôn rồi đó anh @nguyenphuquang
