### ISSUE TITLE
Select game page - Setting popup - Thừa nút "Cancel" và chữ "Logout"

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#143]
Nên thay đổi như hình, tăng kích thước Log_out button lại cho bằng OK button.

![setting popup](https://cloud.githubusercontent.com/assets/22518984/20620144/da3121da-b32a-11e6-9ea1-ae3fc7f3f166.PNG)

**Comment by hiep2x** [comment]
bỏ cancel thì ok. còn chữ logout a thấy để thế này hợp lý hơn để ở cạnh nút Ok
