### ISSUE TITLE
Background sound - Ghi nhận lại sau 100 lần click speaker.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#146]
Nhạc nền bật/tắt chưa đồng nhất theo speaker on/off.
Khảo sát trong 100 lần click có đến 15 lần speaker on nhưng không có nhạc nền.

**Comment by TrhmTan** [comment]
IE edge vẫn chưa được fix.

**Comment by thaopvdinosys** [comment]
@TrhmTan  máy dev test thấy bình thường.không có lỗi xảy ra.
