### ISSUE TITLE
Login page - Trên các trình duyệt khác nhau, thì khác nhau.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#147]
Trông trên Chrome(Version 54) và Opera(Version 41)
![go](https://cloud.githubusercontent.com/assets/22518984/20661657/8e7ae082-b582-11e6-9754-bc392a8eaf70.PNG)
Trông trên Firefox (Vesion 50) và IE(Edge 38). 
Thay đổi lại trên Chrome và Opera để trông "đẹp" như nhau.
![if](https://cloud.githubusercontent.com/assets/22518984/20661658/8e822dd8-b582-11e6-9281-e018d97e2ed3.PNG)

**Comment by thaopvdinosys** [comment]
do mỗi trình duyệt có sự hiển thị khác nhau nên không thể fix trường hợp này.
