### ISSUE TITLE
Game Poker & Domino QQ - Hiệu ứng chip trên bàn chạy sai.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#156]
Start game có 3 User:
Trong giữa quá trình bet có 2User stand up còn 1User ở lại trên bàn.
Bug xuất hiện:
 - Poker: Chip nhiều lần, toàn bộ chip chạy từ vị trí main pot về seat 1.
![d ng di c a chip](https://cloud.githubusercontent.com/assets/22518984/20743677/493a60f4-b70a-11e6-9921-c36c6c7cd907.PNG)
 - Domino QQ: Chip nhiều lần, toàn bộ chip trên bàn chạy hết về kía Dealer thay vì chia làm 2 phần chạy về User winner và Dealer.
![duongdicuachip](https://cloud.githubusercontent.com/assets/22518984/20743678/494487aa-b70a-11e6-9cf0-86acc86ca6b2.PNG)

**Comment by hiep2x** [comment]
@dunglumy123 game poker chị xem sao mới bị lỗi tổng kết trả về gameWinners rỗng nhé.

Tình huống: 3 người đang chơi 1 người đứng dậy, 2 người còn lại đánh đến hết ván.

<img width="447" alt="screen shot 2016-11-30 at 9 39 46 pm" src="https://cloud.githubusercontent.com/assets/7880611/20756585/ccadc68e-b745-11e6-83dc-c212da4be275.png">

**Comment by dunglumy123** [comment]
@TrhmTan : tách 2 bug ra nha Tân, bug của poker vẫn còn, dominoQQ đã fixed
