### ISSUE TITLE
Game Ceme - Cards don't disappear.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#162]
Tình huống: 2 User start game, sau khi chia bài 1 User stand up.
Bug:
 - Tại browser của User được set làm bandar: Sau khi User kia out ra khỏi bàn, phải chờ timeline hết lúc này card mới open. Nên end game sau khi không còn ai trong bàn.
 - Tại browser của User đã stand up, thì vẫn thấy 2 combo cards trong hình cho đến khi game tiếp theo được start.
![109](https://cloud.githubusercontent.com/assets/22518984/20784661/57d68394-b7ce-11e6-904c-9f38dddf16e7.PNG)
Game thứ 150: diễn ra giữa Test9 và Test10. Test10 stand up.
Card game còn xuất hiện đến ván game 151(bên dưới).
![110](https://cloud.githubusercontent.com/assets/22518984/20784664/5bb12d70-b7ce-11e6-8d02-613383dbf0e2.PNG)

**Comment by TrhmTan** [comment]
@thaopvdinosys 
Khi Test10 stand up, và trong bàn xuất hiện thêm Test7.
Card ở vị trí trên hình đã biến mất, nhưng game tiếp theo lại không start được.

**Comment by hiep2x** [comment]
@dunglumy123 Chị Dung, ván 2 người chơi 1 người standup em ko thấy trả về onEndGame.
