### ISSUE TITLE
IE - Khi sử dụng Browser để chơi game, kết quả là bị treo hoặc màn hình chuyển màu tối đen. 

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#166]
Khi Start game với nhiều User cùng tham gia game. IE bắt đầu game chậm và dần tối đen màn hình.

**Comment by thaopvdinosys** [comment]
@Tân,chơi trên 2 trình duyệt IE, EDGE đều bình thường

**Comment by TrhmTan** [comment]
=.=" chắc do mở quá nhiều Browser nên IE, FF chịu không nổi... Chrome và Opera thì vẫn bình thường.
