### ISSUE TITLE
Game Domino - Hiệu ứng Chip trên bàn chạy sai.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#167]
Start game có 3 User:
Trong giữa quá trình bet có 2User stand up còn 1User ở lại trên bàn.
Bug xuất hiện:
 - Domino QQ: Chip nhiều lần, toàn bộ chip trên bàn chạy hết về kía Dealer thay vì chia làm 2 phần chạy về Winner và Dealer.
![duongdicuachip](https://cloud.githubusercontent.com/assets/22518984/20743678/494487aa-b70a-11e6-9cf0-86acc86ca6b2.PNG)

**Comment by hiep2x** [comment]
@TrhmTan e check lại hộ a bản mới nhất còn bị nữa ko nhé, a vừa check thì ko bị.
