### ISSUE TITLE
Game Poker - Hiệu ứng sáng sai card.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#179]
Combo cards để win trong game này phải là Flush (Diamonds) 
Được ghép từ 3 card  giữa bàn và 2 card trên tay User. (Trừ card 5D và 9C)
Và không chạy hiệu ứng hiện tên combo cards win.
![sang sai card](https://cloud.githubusercontent.com/assets/22518984/20922794/024a9750-bbdc-11e6-9853-eddb1e81f304.PNG)

**Comment by hiep2x** [comment]
@TrhmTan em gặp trường hợp này lần nữa thì paste giúp anh cái log vào đây để anh check nhé. Như em đã làm ở bug #118 ấy nhé.

**Comment by TrhmTan** [comment]
@hiep2x, Game ghi nhận lại combo card Flush không chạy hiệu ứng.
Log: `https://drive.google.com/open?id=0B1NczfWkep_qVl9YWHlCNjRla2s`

**Comment by TrhmTan** [comment]
Combo card win: Flush, không chạy chữ a. @hiep2x .
