### ISSUE TITLE
Game Poker - Chỉ hiển thị hiệu ứng bộ bài thắng khi có đủ bộ 5 lá trên bàn

### ISSUE THREAD

**Issue by hiep2x** [nguyenphuquang/cardgame#18]

**Comment by TrhmTan** [comment]
Em hiểu ý anh. @hiep2x, nhưng dù đủ 5 lá bài của dealer chia thì khi các User bỏ bài hết chỉ còn 1 người thì cũng ko cần hiện hiệu ứng thông báo tên bài thắng, chỉ cần thông báo chổ người thắng.

**Comment by TrhmTan** [comment]
Sau khi tham khảo ý kiến chị Dung, em đã closed con bug này
