### ISSUE TITLE
Register - Cần chuyển con trỏ chuột từ Confirm password sang nút Next với thao tác Tab hoặc Enter.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#194]
Hiện tại, khi điền hết các thông tin ở 3 step, User ấn Enter thì page sẽ reload lại trang chọn login hoặc register.
Mong muốn khi User thao tác bằng bàn phím thì User có thể sử dụng các nút Tab và Enter để nhảy text box và qua Step.

**Comment by hiep2x** [comment]
@TrhmTan  Khi điền xong text cuối, nhấn phím Enter nếu hợp lệ thì next sang page tiếp theo.

**Comment by TrhmTan** [comment]
20/02/2017 @hiep2x , ở Step 2 điền thông tin đầy đủ đến text box cuối cùng ấn phím Enter không chuyển page như Step 1.
User phải click lại con trỏ chuột vào vị trí dãy số phone và ấn Enter mới được sang Step 3.
