### ISSUE TITLE
Game Domino QQ - Hiệu ứng chữ Side pot trên bàn bị che khuất.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#212]
![side pot](https://cloud.githubusercontent.com/assets/22518984/21414674/14b2a7ac-c834-11e6-9a14-19d6187955ac.PNG)

**Comment by hiep2x** [comment]
@TrhmTan A vừa check lỗi này thì hết rồi. E check lại xem còn bị ko nhé.

**Comment by TrhmTan** [comment]
Tại vị trí side pot như trên hình vẫn còn bị che, @hiep2x 
Xác nhận sau khi check bản build lúc 3g ngày 28/12/2016.
Và khi em check đến Main pot cũng bị chip đặt nằm trên.
![main pot](https://cloud.githubusercontent.com/assets/22518984/21517656/54a4a7aa-cd13-11e6-831e-c8762a0f0f9b.PNG)

**Comment by TrhmTan** [comment]
Main pot và side pot vẫn còn bị che khuất.
![min chip](https://cloud.githubusercontent.com/assets/22518984/22017562/6f5be75a-dcdd-11e6-8253-4e765174401a.PNG)
![min chip01](https://cloud.githubusercontent.com/assets/22518984/22017563/6f5d680a-dcdd-11e6-89b8-16ffee760829.PNG)
![min chip02](https://cloud.githubusercontent.com/assets/22518984/22017564/6f60769e-dcdd-11e6-8d0d-6fd0bbbb7708.PNG)

**Comment by TrhmTan** [comment]
@hiep2x 
Domino QQ và Poker vẫn còn xuất hiện những kiểu chip nằm trên chữ như thế này!
![side_pot_07-02](https://cloud.githubusercontent.com/assets/22518984/22689372/566dd578-ed63-11e6-8b3f-6fb29ada694d.PNG)
