### ISSUE TITLE
Game Domino QQ - Khi thắng Side Bet thì không có End Game.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#220]
Round1 User đã cược Side Bet= 35, Combo card = Murni Kecil => User thắng Side Bet.
Nhưng khi End Game không có bất kỳ hiệu ứng nào!
Video: `https://drive.google.com/open?id=0B1NczfWkep_qM1llaVJoUTZrR1U`
Log: `https://drive.google.com/open?id=0B1NczfWkep_qMVRaU1NFdl96R0E`
![sidebet01](https://cloud.githubusercontent.com/assets/22518984/21481150/01f10242-cb97-11e6-83fb-95e3ee445cc0.PNG)
![sidebet02](https://cloud.githubusercontent.com/assets/22518984/21481152/01f246de-cb97-11e6-95b6-51bc5b0cf928.PNG)

**Comment by thaopvdinosys** [comment]
@TrhmTan , kiểm tra lại lỗi này nha, dev test thấy có sidebet hay không thì cũng bình thường.
