### ISSUE TITLE
Game Poker - Chữ Jackpot bị che.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#229]
![jackpot](https://cloud.githubusercontent.com/assets/22518984/21706080/e5486b9a-d3f6-11e6-8a11-1882592c4b46.PNG)

**Comment by TrhmTan** [comment]
Tại vị trí User trung tâm màn hình khi cùng win jackpot với những User bên cạnh thì chữ Jackpot không nên để bị che.
![jackpotl1](https://cloud.githubusercontent.com/assets/22518984/21793885/f2f5162e-d727-11e6-96c2-e61f1152adb6.PNG)

**Comment by TrhmTan** [comment]
@hiep2x , Chổ em khoanh đỏ, ý là đối với User đang ngồi xem trên bowres của họ để chơi game.
Thì hiệu ứng trên máy phải hiện full và không hiện đầy đủ.

**Comment by hiep2x** [comment]
@TrhmTan  Bản a mới fix là để user của mình cao nhất ko bị che
