### ISSUE TITLE
Game Poker - Thiếu sự đồng bộ cách xếp lớp số thưởng win side pot.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#241]
![coinpoker](https://cloud.githubusercontent.com/assets/22518984/21846881/bc6f8ce2-d82b-11e6-82eb-29f895c3ed45.PNG)

**Comment by thaopvdinosys** [comment]
@TrhmTan  Việc xuất hiện theo thứ tự kết qủa user, và không theo 1 trật tự nào, user nào trước trong danh sách thì sẽ trên, nên bug này sẽ không fix.
