### ISSUE TITLE
Game Poker - Trừ sai khi User bet.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#243]
Game Poker:
Start Game với 4 User: T8: 62, T6: 468, T7: 712, T9: 384.  Ở vòng bet thứ 3:
T8 bet (6); T6 raise (12); T7 raise 24; T9 raise 50.
T8 call 44; T6 raise (100); T7 saise 200; T9 call 150 (là sai). Nút call phải call giới giá trị 150 +24.
Vì mức tổng chip bet trong vòng này cao nhất là của T7 với 24 + 200 = 224.
Nên tại vị trí sai là: ![callbutton](https://cloud.githubusercontent.com/assets/22518984/22234004/460fb8a0-e227-11e6-857d-7b5aa0cdcdd5.PNG)

Video: `https://drive.google.com/open?id=0B1NczfWkep_qdUlqUFRaWG5UTlE`
Log: `https://drive.google.com/open?id=0B1NczfWkep_qT3V3TXE3a0VZMEU`

**Comment by thaopvdinosys** [comment]
@TrhmTan  theo tham khảo 1 số game poker, thì số tiền tố là số tiền đã bet trước đó cộng thêm số tiền bù vào cho đủ số tiền bet, như vậy thì T7 rise 200 tức là số tiền tối đa của T7 bet (176+24) chứ không phải 224,Như vậy T9 call 150 là tính tiền đúng.

**Comment by TrhmTan** [comment]
@thaopvdinosys, vậy sau khi T9 click vào nút "call 150" thì ở vị trí tương ứng T9 trên bàn có item "C:224" tức là mức bet tối đa trong Round bet này hiện tại của T9 đã bet là 224. Trong khi ở game này T9 chỉ mới bet 50 và call 150 => T9 đã bỏ ra 200 chip thì sao lại để là 224 chip?

**Comment by thaopvdinosys** [comment]
Cái này để xem và chỉnh lại cho đúng, nhưng mức bet tối đa trên bàn chỉ là 200
