### ISSUE TITLE
Firefox - "Buy in" popup - giá trị min max nằm lệch vào trong trên thanh scroll bar

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#25]
- Trong tất cả các trình duyệt: nút cuộn đặt ở vị trí min - max,
        các con số đều bị lệch sang phải(min) và trái(max).
- Chữ "Buy in" lệch lên trên cần chỉnh xuống dưới.

![lech_text](https://cloud.githubusercontent.com/assets/22518984/19504914/5cfa80b2-95e8-11e6-96ab-aac0586b10ba.PNG)

**Comment by hiep2x** [comment]
số tiền buy-in tạm thời để cố định.
