### ISSUE TITLE
Game Domino QQ - 2 nút call và raise bị ẩn dù chip vẫn còn đủ.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#255]
Video: `https://drive.google.com/open?id=0B1NczfWkep_qcWdpa19hbmpzRWs`
Log: `https://drive.google.com/open?id=0B1NczfWkep_qYTVTbEtPSXR0dlE`
![buttonan](https://cloud.githubusercontent.com/assets/22518984/22243971/42e09570-e25c-11e6-8833-5dcb6160f71e.PNG)

**Comment by thaopvdinosys** [comment]
@TrhmTan  em check xem lại có rule nào không, hiện tại a test hoài ko thấy
