### ISSUE TITLE
Game Poker - Gift shop - Đối với Viewer đang để hiệu ứng chạy không đúng vị trí bắt đầu.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#256]
Khi Viewer tặng quà cho User đang ngồi trong bàn, thì hiệu ứng chạy xuất phát từ người ngồi ở vị trí trung tâm.
1.Nên để Game Log (ở góc trái dưới màn hình) ghi nhận lại hành động này của các User.
2.Nên chọn 1 vị trí cố định khác để làm nơi bắt đầu chạy hiệu ứng tặng quà.

**Comment by thaopvdinosys** [comment]
Viewer sẽ không đươc tặng quà cho những người chơi khác trong game.
