### ISSUE TITLE
Game Poker - Gift shop - Nhiều vật phẩm quà tặng có kích thước quá to khi bắt đầu.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#257]
- Gạch.
 - Dép.
Chúng đều có kích thước quá to. Có thể lấy Dealer làm chuẩn để canh lại kích thước các quà tặng.
Ví dụ vậy còn có quả trứng, bánh kem trắng 3 tầm, ly bia, tách coffee, và 3 ly cocktail cần điều chỉnh nhỏ lại 1 chút.
![g ch](https://cloud.githubusercontent.com/assets/22518984/22297529/2f13d148-e350-11e6-81c6-5ce3413b21f0.PNG)
![dep](https://cloud.githubusercontent.com/assets/22518984/22297528/2efbe66e-e350-11e6-9a7c-8b95f57dd1b4.PNG)

**Comment by thaopvdinosys** [comment]
Bug này do resource đang bị lỗi, tạm thời bỏ resource này ra.Version tiếp theo sẽ fix.

**Comment by TrhmTan** [comment]
@thaopvdinosys , effect vẫn chưa chạy mượt, kếu thúc animation các quà tặng dịch nhảy vị trí và thun nhỏ lại. Đáng kể nhất là quà tặng mảnh nhỏ dưa hấu.
Video: `https://drive.google.com/open?id=0B1NczfWkep_qUHliU01obk9na2c`
