### ISSUE TITLE
Game Poker - Profile - Khoảng chác của bảng khác nhau.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#263]
Nếu lấy Dealer làm chuẩn thì xét thấy 2 bảng khác nhau ở kích thước và cả độ lớn.
Theo ảnh Demo => thì:
 - Chỉnh lại ảnh avatar(Trump): canh lại lề sát theo line bên dưới, 
                  ảnh điều chỉnh theo hình vuông, không biến dạng.
 - Thay đổi icon edit của avatar.
 - Cân lại phông nền của những dòng thông tin dưới đường line.
 - Thay đổi đường line như ảnh demo.

![profile](https://cloud.githubusercontent.com/assets/22518984/22638238/62a450be-ec79-11e6-9e1a-d4b1e4438656.PNG)

**Comment by TrhmTan** [comment]
@hiep2x , icon edit  avatar đã biến mất.
Cơ bản là cái popup profile hiện tại to hơn và vị trí cũng không giống trong ảnh chị Thúy gửi qua cho bên em.
![profile_09-02](https://cloud.githubusercontent.com/assets/22518984/22768063/1458fe92-eeb2-11e6-90ae-cd02c6543dd5.PNG)

**Comment by hiep2x** [comment]
@TrhmTan Chức năng edit avatar tạm thời chưa có em nhé, nên anh ko show nút Edit Avatar.
