### ISSUE TITLE
Game Poker + Domino QQ - Sau khi User cược Side_bet, combo button được load lại

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#267]
Sau khi User cược Side_Bet => SỐ chip thay đổi => có thể các button đang show không còn đúng.
=> tùy vào các trường hợp sẽ ẩn cây Slider, các button "Raise" và "Call".
![combo button](https://cloud.githubusercontent.com/assets/22518984/22723737/6d3bab5a-edf3-11e6-9de0-49e8efb9cbb9.PNG)

**Comment by hiep2x** [comment]
@TrhmTan e cho a video trường hợp cụ thể nha.
