### ISSUE TITLE
Game Poker - Hiệu ứng chạy vị trí ghế ngồi

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#27]
Khi click chọn những vị trí mong muốn nhưng hiệu ứng chạy không chuẩn xác.

Video: [https://drive.google.com/open?id=0B1NczfWkep_qQXNIZWliQV91dkU](url)

![thu tu ghe](https://cloud.githubusercontent.com/assets/22518984/19509986/8019fc94-960b-11e6-8410-98fe1611a6ff.PNG)

**Comment by dunglumy123** [comment]
đã fix
