### ISSUE TITLE
Game Poker - Tại Seat 2 và Seat 3 khi end game còn để lại các item (Check/Call/Raise) trên bàn 1 lúc rồi mới mất.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#279]
Trong hình ảnh bên dưới, các card của User testing1 và testing 5 bị các dấu check (có thể là chữ C: call, R: raise) nằm đè lên trong khoảng thời gian đầu của hiệu ứng end game.
![checkin278](https://cloud.githubusercontent.com/assets/22518984/23201624/f5acd2c4-f90c-11e6-9355-34766aa15a7c.PNG)
![checkin279](https://cloud.githubusercontent.com/assets/22518984/23201309/9d6e172c-f90b-11e6-9469-ee4d69410a43.PNG)

**Comment by hiep2x** [comment]
@TrhmTan Tân cho a video lỗi này để a check nhé.

**Comment by TrhmTan** [comment]
![image](https://cloud.githubusercontent.com/assets/22518984/23347642/46c01e60-fcd6-11e6-850b-9c5ac6d33223.png)

**Comment by TrhmTan** [comment]
@hiep2x , khi end game thì các icon "X" Fold, "D" Dealer, "C" Call vẫn tồn tại, nên bỏ như các icon khác (Check, Allin, Bet).
![acc](https://cloud.githubusercontent.com/assets/22518984/23391694/568b2e24-fda9-11e6-8678-c2d65711d01a.PNG)
