### ISSUE TITLE
Game Ceme - Minimize vào lúc bắt đầu start game.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#283]
1 trong 2 User đã minimize trước lúc bắt đầu game, và chờ đến khi start game thì chuyển tab mở Browser của User đã minimize trước đó lên sẽ cho ra kết quả như hình ảnh bên dưới.
![minimize](https://cloud.githubusercontent.com/assets/22518984/23394542/661c6bd8-fdbc-11e6-93de-ddaf63f7b977.PNG)

**Comment by hiep2x** [comment]
@thaopvdinosys khi tab webbrowser trở về trạng thái active, anh check thấy ở event **onUpdateTable** trả về có **timeout = null**
em check lại trả về giá trị timeout đúng nhé

**Comment by TrhmTan** [comment]
- Trong thời gian bet chip, sau khi minimize rồi bật lên lại chồng chip đã thay đổi chip và bị lệch.
- Trong thời gian chờ end game, minimize 2 lần, xuất hiện thêm 2 card ở bên cạnh?! (5s cuối và chỉ 1 vị trí)
- Trước chọn chip khác 1, sau minimize lên chip chọn bet quay lại chip min của room.
Video: `https://drive.google.com/open?id=0B1NczfWkep_qbE54SV9lY2RLOHc`
![cardsan](https://cloud.githubusercontent.com/assets/22518984/23491527/5f40fccc-ff31-11e6-959d-3f37baf3fc52.PNG)
![chips](https://cloud.githubusercontent.com/assets/22518984/23491530/650c65ec-ff31-11e6-9269-f6ff8e4c8d43.PNG)
