### ISSUE TITLE
Vị trí text hiện thị số tiền của người chơi.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#289]
Tại trang select game: ![select game page](https://cloud.githubusercontent.com/assets/22518984/23688290/368f7fa6-03e6-11e7-874b-e745e175165f.PNG). Tại trang lobby:![lobby page](https://cloud.githubusercontent.com/assets/22518984/23688293/400bb96e-03e6-11e7-8ddf-f5749e03692f.PNG)

Tại trang room: 
 - Poker: ![poker room](https://cloud.githubusercontent.com/assets/22518984/23688299/4d39c1e4-03e6-11e7-994b-39c9021e82d8.PNG)
 - Ceme: ![ceme room](https://cloud.githubusercontent.com/assets/22518984/23688304/559b131a-03e6-11e7-9f94-513f4fadc7cd.PNG)
 - Domino QQ: ![dominoqqroom](https://cloud.githubusercontent.com/assets/22518984/23688308/5ef1a65e-03e6-11e7-8faa-caa1c72b70a7.PNG)

-Sử dụng chung 1 loại đồng tiền.
-Chỉnh canh giữa cho tất cả các text box.

**Comment by TrhmTan** [comment]
Hiện tại vị trí tại Lobby giống như trong bất kỳ room Ceme nào.

**Comment by hiep2x** [comment]
@TrhmTan  bug này sửa luôn ở bản design mới nha.

**Comment by TrhmTan** [comment]
@hiep2x , ok Anh!
