### ISSUE TITLE
Register - Nhập sai vẫn tạo account được. Step2 với các thông tin bị chồng chéo và phải nhập lại.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#296]
Step 3, nhập sai thông tin Reference game account vẫn hoàn thành được việc tạo account.
Với text box này cần nhập đúng hoặc để trống.
![register06](https://cloud.githubusercontent.com/assets/22518984/23897529/216473d0-08e0-11e7-8a4a-b6c93241734a.PNG)
Trường hợp khác, khi đang ở step3, quay lại step1 sửa password và sau khi qua step2 thì như hình bên dưới. Và thông tin đã nhập tuy trông thấy nhưng bị xem như mất và phải nhập lại.

Video: `https://drive.google.com/open?id=0B1NczfWkep_qSlNpaU1GNjlvNW8`
![step2chongkytu](https://cloud.githubusercontent.com/assets/22518984/23897380/850c93a0-08df-11e7-9736-76dcd7e7c11d.PNG)

**Comment by hiep2x** [comment]
@TrhmTan bug này đã fix, a sẽ up ở bản design mới nhé

**Comment by TrhmTan** [comment]
Ok anh!
