### ISSUE TITLE
Game Poker - Room - Chọn ghế - "Buy in" popup: Thanh cuộn ngang bị lỗi.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#3]
Khi kéo đến gần các cột mốc giá trị biên, thì giá trị trên nút cuộn ngang không tăng hay giảm theo. 
Khi click chuột vào 2 button "+" "-", cơ số thay đổi lớn.
Mong muốn:
- Khi giữ chuột kéo, giá trị trên nút cuộn ngang luôn thay đổi đều trên thanh cuộn.
- Khi click chuột vào 2 button "+" "-", cơ số thay đổi là 1 đơn vị.
  Video minh họa bên dưới:
  [https://drive.google.com/open?id=0B1NczfWkep_qMWJTcFBtQndWcTQ](url)

**Comment by hiep2x** [comment]
1. Do textfield vừa thay đổi content vừa di chuyển nên đôi khi kéo để thay đổi mức cược thì textfield chỉ di chuyển mà content ko thay đổi (lúc bị lúc ko)

Giải pháp hiện tại: cố định vị trí textfield ở bên phải, ko di chuyển theo nút kéo nữa.
1. Mỗi lần +/- chỉ thay đổi 1 đơn vị có nhỏ quá ko nhỉ? Nếu ở bàn chơi cược mức độ lớn (bàn cược từ 20.000 đến 500.000 chẳng hạn) thì anh nghĩ player cũng ko cần thay đổi từng đơn vị một như vậy). Thầy @nguyenphuquang nghĩ sao ạ?

**Comment by hiep2x** [comment]
Đã commit sửa phần 1 lên svn

**Comment by dunglumy123** [comment]
issue này là khi kéo process bar số trên process bar ko thay đổi, chỉ thay đổi khi buông tay ra. bug này chị đã fix rồi mà chưa note ở trên đây, e fix gì vậy H?

**Comment by hiep2x** [comment]
Ủa, chị fix rồi? Thứ nhất là em ko thấy chị báo là đã sửa lỗi này rồi. Thứ 2 là em update svn mới nhất về vẫn thấy bị lỗi như vậy, chứ có thấy sửa rồi đâu?

**Comment by TrhmTan** [comment]
Hiện tại em thấy, kéo về biên trái và giữ chuột thì luôn gặp tình trạng bị giữ cơ số min không thay đổi.
