### ISSUE TITLE
All Popup - Chưa theo đồng bộ về style ở từng page. [New Design]

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#304]
Trừ 2 game Poker và Ceme vẫn giữ các kiểu popup cũ.
Còn 1 vài cái cần thay đổi như Setting ở Select page, Game Domino QQ: Gift shop, Bet, SIde bet, và confirm.
![giao di n popup](https://cloud.githubusercontent.com/assets/22518984/24029390/3adc5df8-0b08-11e7-920d-a6a55a26fb19.PNG)

**Comment by hiep2x** [comment]
@TrhmTan em check lại giao diện mới, nếu còn bị thì em comment cụ thể chưa đồng bộ chỗ nào nhé.

**Comment by TrhmTan** [comment]
@hiep2x ,Các popup của game Domino QQ không có sự thay đổi theo style của chị Thúy miêu tả là sẽ đồng bộ xanh hết.

**Comment by hiep2x** [comment]
@TrhmTan chờ chị Thúy design các popup còn lại đã nhé.
