### ISSUE TITLE
Game Poker - Khi end game với trường hợp không show card.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#307]
Khi end game, với trên bàn các User đã fold => user còn lại duy nhất sẽ là winner.
Dù là đường hợp đặc biệt Winner có jackpot hay win side bet thì Card trên bàn và Card trên tay user cũng không cần phải sáng lên như kiểu show combo card win.
Tắt bớt hiệu ứng sáng và đẩy card lên trong trường hợp này.
![end_game](https://cloud.githubusercontent.com/assets/22518984/24142654/c65fec2e-0e59-11e7-9e69-af6bd4398266.PNG)

**Comment by thaopvdinosys** [comment]
Trường hợp này lúc trước có nói là khi user thắng các trường hợp đặc biệt thì phải show card lên mà.

**Comment by TrhmTan** [comment]
Vì em thấy ở Zynga ko có chạy hiệu ứng, còn với trường hợp đặc biệt thì chắc vẫn phải show.

**Comment by thaopvdinosys** [comment]
@TrhmTan  show card là phải có hiệu ứng chứ Tân

**Comment by TrhmTan** [comment]
@thaopvdinosys Áp dụng trường họp này trên game Zynga, bên đó phân định rõ ràng 2 cách End Game.
-Bên trái là hình ảnh cho thấy khi end game với 3 User đều show card trên tay với 1 User đã fold, và hiệu ứng sáng viền combo card win + tên combo.
-Bên phải là hình ảnh cho thấy khi end game với 3/4 User đã fold trước khi Dealer show hết 5 card trên bàn. User duy nhất còn lại win game và chỉ có hiệu ứng của tiền cược đang nằm ở khu vực giữa bàn bay về hướng User win. => Dealer chia 0 card hay 5 card, nếu như chỉ còn 1 User thì hiệu ứng chạy ở khu vực giữa bàn chỉ có tiền cược.

![end_game01](https://cloud.githubusercontent.com/assets/22518984/25041798/e3956850-213c-11e7-85c1-1f6437c8ac41.PNG)
