### ISSUE TITLE
Trên trang loading vẫn chưa được gắn effect ở trên và dưới. [New Design]

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#310]
![light_spots](https://cloud.githubusercontent.com/assets/22518984/24278905/5d342bd0-1079-11e7-94fc-5cbde5514513.PNG)

**Comment by hiep2x** [comment]
@TrhmTan scene loading làm gì có effect đèn nháy chú? Trang này chỉ để tĩnh thôi nhé.

**Comment by TrhmTan** [comment]
Em nghĩ đơn giản, khi có sẽ đẹp hơn!
