### ISSUE TITLE
Game Domino QQ - Xem xét lại con số show trong nút Call.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#311]
Với 3 Gamer T1 (907), T2 (685), T3 (578) start 1 ván như sau:
Round 1 cả 3 bet 10. (T1 còn 897; T2 còn 675; T3 còn 568)
Round 2 luân phiên 3 User bet các lượt raise liên tiếp nhau:
 - T1 bet 10    ; T2 raise 20  ; T3 raise 40   (T1 còn 887; T2 còn 655; T3 còn 528).
 - T1 raise 80  ; T2 raise 160; T3 raise 320 (T1 còn 807; T2 còn 495; T3 còn ).
 - T1 raise 640; T2, ![call_button](https://cloud.githubusercontent.com/assets/22518984/24288895/adaf681c-10b1-11e7-85fa-bcf4e66742a2.PNG) dù việc T2 còn 495>480 
Nhưng nếu nút "Call 480" của T2 trong lượt này được show lên là sai!

Vì T1 đã bỏ ra 10+80+640 = 730 để bet trong round 2;
Còn T2= 20+160+480 = 660 < T1 => nút "Call 480" ẩn là đúng! 
Nhưng phải xem xét lại nếu nút Call trong trường họp này phải show lên con số đúng là 730-180= 550.

**Comment by thaopvdinosys** [comment]
@TrhmTan  bug này đã được fix theo rule tính tiền của game Poker.Tân kiểm tra lại cho kỹ nha.
