### ISSUE TITLE
Select Game page - Effect chạy sai khi User chọn 1 game. [New Design]

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#312]
Hiệu ứng Line đèn nháy sáng đã tắt.
Khi click chọn 1 game bất kỳ, hiệu ứng chạy sai, logo và chữ không sáng và bật to như trước.
Chọn Logo để vào Game Poker, chỉ có tên Game chạy vào giữa còn Logo thì không.
Chọn Game Domino QQ, do đã bị sai Logo với Ceme, khi click chọn thì 3 logo game thay đổi thành Logo Game Ceme.
Chọn Game Ceme, không thấy chạy effect nào.
<Hình ảnh Comment bên dưới mô tả lại Bug>

**Comment by TrhmTan** [comment]
![ceme_01](https://cloud.githubusercontent.com/assets/22518984/24344277/e548e376-12f4-11e7-994e-4f1dfbbbd08e.PNG)
![poker_01](https://cloud.githubusercontent.com/assets/22518984/24344323/235bd132-12f5-11e7-9518-b6e14ea040ae.PNG)
![domino_qq_01](https://cloud.githubusercontent.com/assets/22518984/24344350/49759c5e-12f5-11e7-9256-09c875e044f7.PNG)

**Comment by TrhmTan** [comment]
@hiep2x Line đèn trên đã đổi style? Kiểu đèn sáng đuổi này trông không đẹp so với style cũ.

**Comment by hiep2x** [comment]
@TrhmTan Style cũ là a tự nghĩ ra. Còn kiểu đuổi này là theo yêu cầu của design nhé. Làm thế này thì performance tốt hơn.

**Comment by TrhmTan** [comment]
@hiep2x  Ok, Anh!
