### ISSUE TITLE
[New Design] Game Ceme - Icon hình nhân không chạy.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#313]
Có thể loại bỏ con số trong cột Player bằng sự biển diễn của các icon bên cạnh là đủ.
![members](https://cloud.githubusercontent.com/assets/22518984/24352864/647650a0-1315-11e7-9edd-234c9d5f91ac.PNG)

**Comment by thaopvdinosys** [comment]
@hiep2x  anh Hiệp xem bug này giúp em nha.
