### ISSUE TITLE
[New Design] Game Domino QQ - Nền của chip trên bàn đã biến mất.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#314]
![nen_chip](https://cloud.githubusercontent.com/assets/22518984/24388199/49bddf38-13a3-11e7-87bb-8d11d7bad32e.PNG)

**Comment by TrhmTan** [comment]
@hiep2x Chưa thấy thay đổi, chắc là vẫn chưa được build lên đó a.Hiệp!

**Comment by hiep2x** [comment]
@TrhmTan bản mới sẽ có. a chưa up vì còn đang sửa giao diện khác chưa xong.
