### ISSUE TITLE
Game Domino QQ - Game Poker: Time line đang start trước khi card trên tay User show.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#315]
Khi bắt đầu 1 ván trên cả 2 game (Poker hay Domino QQ),
Người chơi phải chờ Dealer chia card, xếp card và show card trên tay User, 
Nhưng thời gian đã được tính từ lúc dealer chia lá bài đầu tiên. 
< Game Domino QQ >_< Đến lúc VN-test07 trông thấy card trên tay thì đã mất 1 khoảng time nhất định.>
< Game Poker >_< Cũng giống như vậy nhưng do chạy ít effect hơn nên time ít mất hơn.>
![start_game](https://cloud.githubusercontent.com/assets/22518984/24395907/85495eec-13cb-11e7-8eb7-13660f7971a2.png)

**Comment by thaopvdinosys** [comment]
Phần này do hiệu ứng chạy, chia bài.chỉ có thể giảm thời gian hiệu ứng xuống hoặc tắt luôn hiệu ứng.
