### ISSUE TITLE
Avatar - Image to hơn vùng mặc định show avatar và che mất edit icon.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#326]
Tương tự với góc show avatar ở góc trái trên.
![lech_pixel](https://cloud.githubusercontent.com/assets/22518984/24895714/133ae3f6-1ebc-11e7-8af2-9c76baaf1587.PNG)

**Comment by hiep2x** [comment]
@TrhmTan bug này a đã sửa ở giao diện mới rồi nhé.

**Comment by TrhmTan** [comment]
Ok! @hiep2x ,E sẽ chờ chuyển đổi giao diện lên hết 1 lần.
