### ISSUE TITLE
Avatar - Không thay đổi avatar khi User change image lúc ván bài đang diễn ra.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#327]
Trên cả 3 game, đang lúc User1 chơi game cùng User khác, thực hiện hành động edit avatar.
Sau đó chỉ trên browser của User 1 thay đổi, các User khác không nhận thấy sự thay đổi đó.
Riêng game Domino QQ, khi start game tiếp theo, avatar của User1 thì show lại image cũ.
Video: `https://drive.google.com/open?id=0B1NczfWkep_qTkhqRVdPa19jeDg`
![change01](https://cloud.githubusercontent.com/assets/22518984/24905670/f48cf43a-1ede-11e7-869e-7c76734f3945.PNG)

**Comment by thaopvdinosys** [comment]
@TrhmTan : Hiên tại, không làm việc thay đổi avatar user này thì user khác cũng thấy ngay lập tức.

**Comment by TrhmTan** [comment]
@thaopvdinosys : vậy hiện tại, các User khác muốn thấy được sự thay đổi avatar của người khác thì:
"phải" chờ người đó đứng lên và ngồi lại.

**Comment by thaopvdinosys** [comment]
@TrhmTan uhm,

**Comment by TrhmTan** [comment]
@thaopvdinosys , vậy trường hợp của trên game QQ là bug, vì sau khi star game sau, avatar của User đó không giữa hình mới mà quay lại sử dụng hình cũ.
