### ISSUE TITLE
[New Design] Game Poker Và Domino QQ - Khi bàn đủ người.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#332]
Vị trí đặt nút View so với room đang full đang sai, và kích thước trên 2 nút trên 2 game cũng khác nhau.
![bug_button](https://cloud.githubusercontent.com/assets/22518984/25037958/3b34946c-2126-11e7-92c5-544699e02b01.PNG)

**Comment by thaopvdinosys** [comment]
@hiep2x  anh Hiệp fix giúp em bug này nha.
