### ISSUE TITLE
Popup - Style của tùy thuộc vào game, Xanh cho riêng Domino QQ và đen cho Ceme và Poker.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#341]
![edit_profile_style](https://cloud.githubusercontent.com/assets/22518984/25169222/6e56dea2-2510-11e7-9d96-5919ac3c4e77.PNG)
![popup_xanh](https://cloud.githubusercontent.com/assets/22518984/25169224/702c71ce-2510-11e7-9f71-76a6399a60fa.PNG)

**Comment by TrhmTan** [comment]
Vẫn còn Popup: Edit profile ở 2 game Poker và Ceme.

**Comment by TrhmTan** [comment]
![popup11](https://cloud.githubusercontent.com/assets/22518984/25699555/f3958b34-30ed-11e7-829c-288d8361c651.PNG)
Trên game Domino QQ vẫn còn 1 popup chưa đổi style.

**Comment by thaopvdinosys** [comment]
@TrhmTan  dialog dạng này nên thống nhất 1 kiểu, không chia ra theo game.

**Comment by TrhmTan** [comment]
@hiep2x , popup Edit profile trong game Domino QQ chưa gắn background mới.
![511](https://cloud.githubusercontent.com/assets/22518984/25930764/555912d4-3632-11e7-94d9-a6648e5e74aa.PNG)
