### ISSUE TITLE
Sound - Một số các thao tác chưa được gắn âm thanh đi kèm.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#358]
Tại các nút bên dưới chưa được gắn âm thanh:
 - Stand up ở trong room Game Poker.
 - ( X) close icon, edit icon, edit profilr icon trong popup "Profile".
 - Tất cả ![edit](https://cloud.githubusercontent.com/assets/22518984/25381966/fa524eb8-29df-11e7-89dc-e60bedbfad69.PNG) trong popup "Edit profile"
 - ![qua](https://cloud.githubusercontent.com/assets/22518984/25381836/745b76d6-29df-11e7-874c-45bc9ae6239d.PNG).
 - Seat ở 2 game Poker và Domino QQ.

**Comment by thaopvdinosys** [comment]
@TrhmTan xem thêm còn chỗ nào thiếu, liệt kê ra để thêm vào luôn 1 lần.

**Comment by TrhmTan** [comment]
Nhắc lại:
 - ![select game page511](https://cloud.githubusercontent.com/assets/22518984/25932611/8519a826-363c-11e7-9b5f-37bf64f5f45f.PNG) từ select game page. Cả 3 nút đều không có âm thanh khi được click.
 - ![profile](https://cloud.githubusercontent.com/assets/22518984/25932614/86d72d78-363c-11e7-9c0c-74e319168483.PNG) 2 Nút này chưa có âm thanh.
 - ![button](https://cloud.githubusercontent.com/assets/22518984/25932708/1ed29b58-363d-11e7-83c0-b13d9b640f8c.PNG), Các nút X để close popup.
 - Icon hộp quà ở lobby page và Help room game Domino QQ![button01](https://cloud.githubusercontent.com/assets/22518984/25933529/7d306ec4-3641-11e7-9835-1a8af8b10845.PNG).
 - Button Send![bo chat](https://cloud.githubusercontent.com/assets/22518984/25933533/86810bf0-3641-11e7-8224-761ccf5f9fb2.PNG)
 - Dấu + - và button Buy in ![buy in](https://cloud.githubusercontent.com/assets/22518984/25933543/a17c86be-3641-11e7-9c33-59f9895fe546.PNG) và slider bet ![add_sup](https://cloud.githubusercontent.com/assets/22518984/25933605/439ab844-3642-11e7-8e55-28e5709a3336.PNG)
 - 2 Button cancel và ok của popup thông báo khi stand up hoặc leave room ![cancel_ok](https://cloud.githubusercontent.com/assets/22518984/25933559/d11e781e-3641-11e7-84a9-a306d189bd02.PNG)
 - ![mini_icon to gift shop](https://cloud.githubusercontent.com/assets/22518984/25933608/4e49ceb0-3642-11e7-996d-60fe2abee0ec.PNG) mini icon nhỏ này.
 - Khi chọn seat ở 2 game Poker và Domino QQ ![pokerseat](https://cloud.githubusercontent.com/assets/22518984/25933617/61827874-3642-11e7-8c76-44da79907f5e.PNG)
 - Button side bet ![sidebet](https://cloud.githubusercontent.com/assets/22518984/25933626/77c221c0-3642-11e7-8baa-2c5fe41b2753.PNG)
 - Sort danh sách player ![sort](https://cloud.githubusercontent.com/assets/22518984/25933645/991565bc-3642-11e7-81ab-d8c8497add64.PNG)

**Comment by TrhmTan** [comment]
@thaopvdinosys  còn sót 1 Popup Confirm trong Game Domino QQ.
![confirm](https://cloud.githubusercontent.com/assets/22518984/25946080/bfb3ee2e-3673-11e7-97e6-4d7c4e0f3a5e.PNG)
