### ISSUE TITLE
Lobby page - Khi các member làm Full room.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#371]
2 nút ![view_button](https://cloud.githubusercontent.com/assets/22518984/25478367/fd9a6826-2b6a-11e7-8803-1f7f2de6985b.PNG) là trạng thái của room, không dùng để thao tác, giống như tín hiệu báo room có đang full người chơi chưa.
![427](https://cloud.githubusercontent.com/assets/22518984/25478262/a11579a6-2b6a-11e7-8deb-f859ad1f7c3f.PNG)

**Comment by hiep2x** [comment]
@TrhmTan  hiện tại chỉ có nút VIEW luôn hiển thị cho các phòng thôi nhé, ko có riêng cho trg hợp phòng Full members.
