### ISSUE TITLE
Game Ceme - List Bandar ở góc show danh sách tên sai.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#385]
Để 4 member khác nhau vào ngồi 4 rooom khác nhau.
 - Bug: Trên bàn thấy ghi nhận show icon set Bandar và biến mất ngay sau đó, ở list đã có danh sách.
 - Dev có thể add thêm chức năng Sort cho các cột của danh sách "List Bandar", hiện tại đang để mặc định sort theo tên của các Member trong danh sách.
![bandar01](https://cloud.githubusercontent.com/assets/22518984/25882652/3f91ffa6-356f-11e7-96f2-5cc26c3c4bd5.PNG)

 - Member cuối cùng đứng dạy vẫn còn giữ tên trong danh sách.
 - Trong hình Member VN-test05 không đước set làm Bandar trong room default3-vn với 63,330.356 chip? Vì danh sách List Bandar không có tên member VN-test05. 

![bandar02](https://cloud.githubusercontent.com/assets/22518984/25882654/4146a90a-356f-11e7-8ebb-7cb12925f37b.PNG)

**Comment by dunglumy123** [comment]
không cần sort nha Tân
