### ISSUE TITLE
Game Donimo QQ - Game log box ghi nhận dữ liệu double.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#57]
![s chip](https://cloud.githubusercontent.com/assets/22518984/19925343/279f5fa6-a122-11e6-87de-1e5a5af938df.PNG)

**Comment by dunglumy123** [comment]
Xem lại tình huống như thế nào? nếu nó thắng 2 pot thì sẽ có 2 hiệu ứng tiền được cộng vô nha
