### ISSUE TITLE
Game Domino QQ - Jackpot sai card

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#60]
![jackpot sai](https://cloud.githubusercontent.com/assets/22518984/19724022/33f0e18c-9ba8-11e6-8b13-fe18299a47d3.PNG)

**Comment by dunglumy123** [comment]
Đọc lại luật: 
2. MURNI BESAR , its means that the total spheres / dots from 4 cards its between 39 until 43
