### ISSUE TITLE
Game Domino QQ - Start Game có Bet không?

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#65]
Bắt đầu game có hiệu ứng từ người chơi các chip bay ra và nằm trên bàn, trước mặt Dealer.
Trước mặt người chơi chưa có action --> chưa cược --> chưa bị trừ chip cược.
=> Chip bay ra từ ban đầu là gì?

Nếu phải Bet một lượng nhất định lúc bắt đầu game nên cho hiện số chip đó trước mặt người chơi, cùng lúc hiệu ứng chip bay về phía Dealer. 
![start game](https://cloud.githubusercontent.com/assets/22518984/19763642/277f1dbc-9c69-11e6-98dc-dfc4a309ceb8.PNG)

**Comment by dunglumy123** [comment]
Cái này là luật của Domino QQ, không phải bug

**Comment by TrhmTan** [comment]
Chờ cột Blind có data
