### ISSUE TITLE
Game poker - Thông báo kết quả của ván bài.

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#7]
Cho hiện thông tin bài thắng cược khi kết thúc 1 ván.
Tên bài thắng cược sau khi được ghép từ tay người chơi và bài ở giữa bàn:
- High Card
- Pair
- Two Pairs
- Three of a Kind
- Straight
- Flush
- Full House
- Four of a Kind
- Straight Flush
- Royal Straight Flush

![report1](https://cloud.githubusercontent.com/assets/22518984/19373587/6513fc80-91ef-11e6-85a7-837f65f2abdd.PNG)

**Comment by hiep2x** [comment]
đã làm tính năng này rồi, đã commit svn hôm 11/10 nhưng chưa cập nhật lên bản client trên server.
