### ISSUE TITLE
Game Poker - Side pot không chạy hiệu ứng

### ISSUE THREAD

**Issue by TrhmTan** [nguyenphuquang/cardgame#92]
video: https://drive.google.com/open?id=0B1NczfWkep_qVHg2THN1bld5T2c

**Comment by hiep2x** [comment]
@TrhmTan trường hợp 1 player/sidepot thì sẽ ko có hiệu ứng em nhé, bởi vì trường hợp đó player ko phải là winner. Từ 2  player/sidepot thì mới có hiệu ứng
